# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1lu2ZY1VYUpPoqWqoKPsbbJP6yYwn6sWa
"""

from sklearn.linear_model import LinearRegression
import numpy as np

# Input: Car Speed (km/h)
X = np.array([[40], [50], [60], [70]])

# Output: Fuel Consumption (L/100 km)
Y = np.array([5, 6, 7, 8])

# Create Linear Regression Model
model = LinearRegression()

# Train the Model
model.fit(X, Y)

# Display Slope and Intercept
print("Slope (m):", model.coef_[0])
print("Intercept (c):", model.intercept_)

# Predict Fuel Consumption at 80 km/h
x_test = np.array([[80]])
prediction = model.predict(x_test)

print("Predicted Fuel Consumption:", prediction[0], "L/100 km")

