# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OpELWniT8wLC28bdi6QYWC0zQW45L9oq
"""

from sklearn.linear_model import LinearRegression

# Dataset
# [Month]
X = [[1],
     [2],
     [3],
     [4],
     [5],
     [6],
     [7],
     [8]]

# Sales in thousands
y = [20, 23, 27, 30, 34, 38, 42, 46]

# Create and train model
model = LinearRegression()
model.fit(X, y)

# Get input from user
month = int(input("Enter Future Month: "))

# Predict sales
sales = model.predict([[month]])

print("Predicted Future Sales:", round(sales[0], 2), "Thousand")