# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OpELWniT8wLC28bdi6QYWC0zQW45L9oq
"""

from sklearn.tree import DecisionTreeRegressor

# Dataset
# [Area, Bedrooms]
X = [[700, 2],
     [900, 2],
     [1100, 3],
     [1300, 3],
     [1600, 4],
     [1900, 4],
     [2200, 5]]

# House prices in Lakhs
y = [18, 23, 29, 34, 42, 50, 60]

# Create and train model
model = DecisionTreeRegressor()
model.fit(X, y)

# Get input from user
area = float(input("Enter Area in sq.ft: "))
bedrooms = int(input("Enter Number of Bedrooms: "))

# Predict price
price = model.predict([[area, bedrooms]])

print("Predicted House Price:", round(price[0], 2), "Lakhs")