# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OpELWniT8wLC28bdi6QYWC0zQW45L9oq
"""



from sklearn.datasets import load_iris
from sklearn.neighbors import KNeighborsClassifier

iris = load_iris()

X = iris.data
y = iris.target

model = KNeighborsClassifier(n_neighbors=3)
model.fit(X, y)

a = float(input("Enter Sepal Length: "))
b = float(input("Enter Sepal Width: "))
c = float(input("Enter Petal Length: "))
d = float(input("Enter Petal Width: "))

result = model.predict([[a, b, c, d]])

print("Iris Flower:", iris.target_names[result[0]])