# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OpELWniT8wLC28bdi6QYWC0zQW45L9oq
"""



import numpy as np
from sklearn.mixture import GaussianMixture

X = np.array([[1], [2], [3], [8], [9], [10]])

model = GaussianMixture(n_components=2, random_state=0)
model.fit(X)

labels = model.predict(X)

print("Data\tCluster")
for i in range(len(X)):
    print(X[i][0], "\t", labels[i])

print("\nMeans:")
print(model.means_)