# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OpELWniT8wLC28bdi6QYWC0zQW45L9oq
"""

from sklearn.tree import DecisionTreeRegressor

# Dataset
# [RAM, Storage]
X = [[2, 32],
     [3, 32],
     [4, 64],
     [4, 128],
     [6, 128],
     [6, 256],
     [8, 256],
     [12, 256]]

# Mobile prices in thousands
y = [8, 10, 13, 16, 20, 25, 32, 40]

# Create and train model
model = DecisionTreeRegressor(random_state=42)
model.fit(X, y)

# Get input from user
ram = int(input("Enter RAM in GB: "))
storage = int(input("Enter Storage in GB: "))

# Predict price
price = model.predict([[ram, storage]])

print("Predicted Mobile Price:", round(price[0], 2), "Thousand")