# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OpELWniT8wLC28bdi6QYWC0zQW45L9oq
"""

from sklearn.naive_bayes import GaussianNB

# Dataset
# [Income, Credit Score, Loan Amount]
X = [[25, 550, 5],
     [30, 580, 6],
     [35, 600, 7],
     [40, 650, 8],
     [45, 680, 10],
     [50, 700, 12],
     [60, 750, 15],
     [70, 800, 18]]

# 0 = Loan Rejected, 1 = Loan Approved
y = [0, 0, 0, 1, 1, 1, 1, 1]

# Create and train Naive Bayes model
model = GaussianNB()
model.fit(X, y)

# Get input from user
income = float(input("Enter Monthly Income: "))
credit_score = float(input("Enter Credit Score: "))
loan_amount = float(input("Enter Loan Amount: "))

# Predict loan status
prediction = model.predict([[income, credit_score, loan_amount]])

if prediction[0] == 1:
    print("Loan Status: Approved")
else:
    print("Loan Status: Rejected")