# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OpELWniT8wLC28bdi6QYWC0zQW45L9oq
"""

from sklearn.datasets import load_iris
from sklearn.linear_model import Perceptron

# Load IRIS dataset
iris = load_iris()

X = iris.data
y = iris.target

# Create Perceptron model
model = Perceptron(random_state=42)

# Train the model
model.fit(X, y)

# Get input from user
sepal_length = float(input("Enter Sepal Length: "))
sepal_width = float(input("Enter Sepal Width: "))
petal_length = float(input("Enter Petal Length: "))
petal_width = float(input("Enter Petal Width: "))

# Predict flower class
prediction = model.predict([[
    sepal_length,
    sepal_width,
    petal_length,
    petal_width
]])

print("Predicted Flower:", iris.target_names[prediction[0]])