# -*- coding: utf-8 -*-
"""Untitled9.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OpELWniT8wLC28bdi6QYWC0zQW45L9oq
"""

import numpy as np
import matplotlib.pyplot as plt
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures

# Data
X = np.array([1, 2, 3, 4, 5, 6, 7, 8]).reshape(-1, 1)
y = np.array([2, 4, 7, 11, 16, 22, 29, 37])

# Linear Regression
linear = LinearRegression()
linear.fit(X, y)
y1 = linear.predict(X)

# Polynomial Regression
poly = PolynomialFeatures(degree=2)
X2 = poly.fit_transform(X)

model = LinearRegression()
model.fit(X2, y)
y2 = model.predict(X2)

# Results
print("Actual\tLinear\tPolynomial")

for i in range(len(y)):
    print(y[i], "\t", round(y1[i], 2), "\t", round(y2[i], 2))

# Graph
plt.scatter(X, y)
plt.plot(X, y1, label="Linear")
plt.plot(X, y2, label="Polynomial")

plt.xlabel("X")
plt.ylabel("Y")
plt.title("Linear vs Polynomial Regression")
plt.legend()
plt.show()